### ISSUE TITLE
Code Issue/Question

### ISSUE THREAD

**Issue by BillCyper** [Xeio/SwlRdbExporter#3]
Hi, I know this is an old tool and probably not much of a concern to you, but I'm experiencing an issue with line 104 of the program.cs

I'm a graphic artist. I couldn't code to save my life. I have entered the path directory and even put in the -i parameter in visual studio, but when I try to run the program, the cmd prompt pops up and gives me this warning.

Unhandled exception. Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument 'rdbexporter.exe'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at RdbExporter.Program.Main(String[] args) in C:\Users\Admin\Desktop\SwlRdbExporter-master\SwlRdbExporter-master\RdbExporter\Program.cs:line 104

C:\Users\Admin\Desktop\SwlRdbExporter-master\SwlRdbExporter-master\RdbExporter\bin\Debug\net5.0\RdbExporter.exe (process 18004) exited with code -532462766.

I've tried building the .exe and running it that way, but it just blips off as soon as I open it. I assume it has to do with the above issue. If you could take some time to help me out, I'd greatly appreciate it.

**Comment by Xeio** [comment]
Are you trying to modify it somehow? Normally you'd want to just download the zip from the [release](https://github.com/Xeio/SwlRdbExporter/releases/tag/v1.1) page and just run the already-complied version via the command line.

**Comment by BillCyper** [comment]
Huh. I haven't found a file that will run through the command line. I
appreciate the info, will start cycling through again.

**Comment by Xeio** [comment]
Make sure you download the "SwlRdbExporter.zip" file from that link, not the ones that say "source code".

**Comment by BillCyper** [comment]
And that would be the problem! Thanks so much for your help!
